services:
  - type: web
    name: nextday-app
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: bash render-build.sh
    startCommand: gunicorn your_application.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: MOCK_MODE
        value: "True"
      - key: DB_ENGINE
        value: "sqlite"
