# Generated by Django 5.2.15 on 2026-06-25 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('image', models.ImageField(upload_to='closet/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('garment_type', models.CharField(choices=[('top', 'ท่อนบน (Top)'), ('bottom', 'ท่อนล่าง (Bottom)')], max_length=16)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('dominant_color_hex', models.CharField(default='#808080', max_length=7)),
                ('dominant_color_rgb', models.JSONField(default=list)),
                ('color_name', models.CharField(blank=True, max_length=32)),
                ('preference_score', models.FloatField(default=0.5, help_text='CBF — ยิ่งใส่บ่อย/ถูกใจ คะแนนสูงขึ้น')),
                ('wear_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DressRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(help_text='อุณหภูมิต่ำสุด (°C)')),
                ('temp_max', models.FloatField(help_text='อุณหภูมิสูงสุด (°C)')),
                ('allowed_styles', models.JSONField(default=list)),
                ('forbidden_rules', models.JSONField(default=list, help_text='เช่น ["no_black_solid", "no_shorts", "no_sporty"]')),
                ('formality_min', models.FloatField(default=0.0, help_text='0=ลำลอง, 1=ทางการมาก')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='outfit.location')),
            ],
            options={
                'ordering': ['location', 'temp_min'],
            },
        ),
    ]
