# Generated by Django 5.2.15 on 2026-06-21 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.6, help_text='เกณฑ์ความมั่นใจขั้นต่ำ')),
                ('lab_min_delta', models.FloatField(default=12.0, help_text='Goldilocks: ระยะสีต่ำสุด')),
                ('lab_max_delta', models.FloatField(default=45.0, help_text='Goldilocks: ระยะสีสูงสุด')),
            ],
            options={
                'verbose_name': 'ตั้งค่า AI',
                'verbose_name_plural': 'ตั้งค่า AI',
                'db_table': 'ai_settings',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('formality_level', models.IntegerField(help_text='ระดับความสุภาพ 1-6')),
                ('allowed_categories', models.JSONField(default=list, help_text='ประเภทเสื้อผ้าที่อนุญาต')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📍', max_length=10)),
            ],
            options={
                'verbose_name': 'สถานที่/โอกาส',
                'verbose_name_plural': 'สถานที่/โอกาส',
                'db_table': 'destinations',
                'ordering': ['formality_level'],
            },
        ),
        migrations.AlterModelOptions(
            name='clothinganalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'การวิเคราะห์เสื้อผ้า (Legacy)', 'verbose_name_plural': 'การวิเคราะห์เสื้อผ้า (Legacy)'},
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/%Y/%m/%d/')),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='wardrobe/crops/%Y/%m/%d/')),
                ('part', models.CharField(choices=[('top', 'ท่อนบน'), ('bottom', 'ท่อนล่าง')], max_length=10)),
                ('garment_type', models.CharField(choices=[('shirt', 'เสื้อเชิ้ต'), ('t_shirt', 'เสื้อยืด'), ('blouse', 'เสื้อผ้า'), ('jacket', 'แจ็คเก็ต'), ('pants', 'กางเกง'), ('shorts', 'กางเกงขาสั้น'), ('skirt', 'กระโปรง')], max_length=20)),
                ('formality', models.IntegerField(default=3, help_text='ระดับความสุภาพ 1-6')),
                ('confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('primary_color_hex', models.CharField(max_length=7)),
                ('color_name_th', models.CharField(blank=True, max_length=50)),
                ('dominant_colors', models.JSONField(default=list)),
                ('lab_l', models.FloatField(default=0)),
                ('lab_a', models.FloatField(default=0)),
                ('lab_b', models.FloatField(default=0)),
                ('bbox_x1', models.IntegerField(default=0)),
                ('bbox_y1', models.IntegerField(default=0)),
                ('bbox_x2', models.IntegerField(default=0)),
                ('bbox_y2', models.IntegerField(default=0)),
                ('aspect_ratio', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'เสื้อผ้า',
                'verbose_name_plural': 'เสื้อผ้า',
                'db_table': 'clothing_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_theory', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits_as_bottom', to='database.clothingitem')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.destination')),
                ('top_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits_as_top', to='database.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ชุดโปรด',
                'verbose_name_plural': 'ชุดโปรด',
                'db_table': 'favorite_outfits',
                'ordering': ['-created_at'],
            },
        ),
    ]
