# Generated by Django 5.2.16 on 2026-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_aisettings_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='fabric_thickness',
            field=models.CharField(choices=[('thin', 'บาง'), ('medium', 'ปานกลาง'), ('thick', 'หนา')], default='medium', help_text='ความหนาผ้า', max_length=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='garment_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Matrix A: เกณฑ์ต่อประเภทเสื้อผ้า'),
        ),
        migrations.AddField(
            model_name='destination',
            name='style',
            field=models.CharField(choices=[('casual', 'สบายๆ'), ('smart_casual', 'สมาร์ทแคชชวล'), ('formal', 'ทางการ'), ('sporty', 'กีฬา')], default='casual', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather',
            field=models.CharField(choices=[('hot', 'ร้อน'), ('mild', 'อุ่นสบาย'), ('cool', 'เย็น/แอร์')], default='mild', max_length=10),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='garment_type',
            field=models.CharField(choices=[('t_shirt', 'เสื้อยืด'), ('polo', 'เสื้อโปโล'), ('shirt', 'เสื้อเชิ้ต'), ('tank_top', 'เสื้อกล้าม / สายเดี่ยว'), ('crop_top', 'เสื้อครอป'), ('jeans', 'กางเกงยีนส์'), ('slacks', 'กางเกงสแล็ก'), ('chinos', 'กางเกงชิโน่'), ('shorts', 'กางเกงขาสั้น'), ('joggers', 'กางเกงจ็อกเกอร์'), ('sweatpants', 'กางเกงวอร์ม'), ('leggings', 'กางเกงเลกกิ้ง'), ('skirt', 'กระโปรง'), ('dress', 'ชุดเดรส'), ('jumpsuit', 'ชุดจั๊มสูท'), ('suit', 'เสื้อสูท'), ('blazer', 'เบลเซอร์'), ('jacket', 'เสื้อแจ็กเก็ต'), ('hoodie', 'เสื้อฮู้ด'), ('sweater', 'สเวตเตอร์'), ('cardigan', 'เสื้อคาร์ดิแกน')], max_length=32),
        ),
    ]
